# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('address', models.TextField(verbose_name='주소')),
                ('location', models.TextField(verbose_name='위도/경도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_bookingposts_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_bookingposts_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
