# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bookingpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpost',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_bookingposts_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
